const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=process.env.TEST_URL||'http://127.0.0.1:8005/';await page.goto(url);await page.waitForFunction(()=>ready);await page.locator('.home-cta').click();
 await page.locator('[name=income]').fill('123200');await page.locator('[name=count]').fill('5');await page.locator('[name=tips]').fill('20000');await page.locator('[name=transport]').fill('18000');await page.locator('[name=memo]').fill('군포역 귀가 계획');
 // Immediate navigation must retain the most recent text, before the debounced photo draft write.
 await page.reload();await page.waitForFunction(()=>ready);await page.locator('.bottom-nav [data-view=diary]').click();assert.equal(await page.locator('[name=income]').inputValue(),'123200');assert.equal(await page.locator('[name=memo]').inputValue(),'군포역 귀가 계획');assert.match(await page.locator('#draft-status').textContent(),/복원/);
 await page.locator('#diary-date').fill('2026-10-06');await page.locator('[name=start]').fill('19:42');await page.locator('[name=end]').fill('01:45');assert.equal(await page.locator('#end-date').inputValue(),'2026-10-07');
 await page.locator('#photos').setInputFiles('icon-192.png');await page.waitForFunction(()=>!PhotoImport.busy,{},{timeout:120000});await page.waitForFunction(()=>document.getElementById('draft-status').textContent.includes('임시 보관됨'));
 // A draft photo survives reload and opens at full size, but a draft is not income yet.
 await page.reload();await page.waitForFunction(()=>ready);assert.equal(await page.evaluate(()=>state.diaries.length),0);await page.locator('.bottom-nav [data-view=diary]').click();assert.equal(await page.locator('#photo-preview img').count(),1);await page.locator('#photo-preview button').click();assert.equal(await page.locator('#photo-dialog').evaluate(d=>d.open),true);await page.locator('#photo-close').click();
 await page.locator('.bottom-nav [data-view=settings]').click();await Promise.all([page.waitForEvent('framenavigated'),page.locator('#check-update').click()]);await page.waitForFunction(()=>ready);await page.locator('.bottom-nav [data-view=diary]').click();assert.equal(await page.locator('[name=income]').inputValue(),'123200');assert.equal(await page.locator('#photo-preview img').count(),1);
 await page.locator('#diary-form [type=submit]').click();await page.waitForFunction(()=>state.diaries.length===1);assert.equal(await page.locator('#month-income').textContent(),'125,200원');assert.match(await page.locator('#latest-diary').textContent(),/125,200원/);await page.reload();await page.waitForFunction(()=>ready);await page.locator('.bottom-nav [data-view=diary]').click();assert.equal(await page.locator('[name=income]').inputValue(),'');
 await page.locator('.bottom-nav [data-view=history]').click();await page.locator('#history-month').fill('2026-10');await page.locator('#history-month').dispatchEvent('change');await page.locator('#history-calendar button[aria-label^="2026-10-06"]').click();assert.equal(await page.locator('.diary-card').count(),1);await page.locator('#history-calendar button[aria-label^="2026-10-05"]').click();assert.equal(await page.locator('.diary-card').count(),0);await page.locator('#history-filter-clear').click();assert.equal(await page.locator('.diary-card').count(),1);
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});for(const tab of ['home','diary','history','settings']){await page.locator(`.bottom-nav [data-view=${tab}]`).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${width} ${tab} overflow`);}}
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: immediate draft restore, photo draft restore, full-size image, draft excluded from income, saving clears draft, latest record, calendar filters, 320/390/768px layouts');
})().catch(e=>{console.error(e);process.exit(1)});
